apiVersion: v2
name: netbird-api-exporter
description: A Helm chart for NetBird API Exporter - Prometheus exporter for NetBird API metrics

type: application

version: 0.1.19

appVersion: "0.1.19"

home: https://github.com/matanbaruch/netbird-api-exporter
sources:
  - https://github.com/matanbaruch/netbird-api-exporter
keywords:
  - netbird
  - prometheus
  - exporter
  - monitoring
  - metrics
annotations:
  category: Monitoring
  # Artifact Hub annotations
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: GitHub Repository
      url: https://github.com/matanbaruch/netbird-api-exporter
    - name: Documentation
      url: https://github.com/matanbaruch/netbird-api-exporter/blob/main/README.md
    - name: Changelog
      url: https://github.com/matanbaruch/netbird-api-exporter/blob/main/CHANGELOG.md
    - name: Issues
      url: https://github.com/matanbaruch/netbird-api-exporter/issues
  artifacthub.io/maintainers: |
    - name: Matan Baruch
      email: matan.baruch@example.com
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/prometheus-community/prometheus
    - url: https://artifacthub.io/packages/helm/grafana/grafana
  artifacthub.io/changes: |
    - Add publishing to artifacthub.io for the OCI package of the helm chart
