blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/matanbaruch/netbird-api-exporter/blob/main/README.md
    about: Check the documentation for setup instructions and troubleshooting
  - name: 🐦 NetBird Docs
    url: https://docs.netbird.io/
    about: NetBird documentation