# GitHub Pages configuration
title: "NetBird API Exporter"
description: "A Prometheus exporter for NetBird API that provides comprehensive metrics about your NetBird network"
url: "https://matanbaruch.github.io"
baseurl: "/netbird-api-exporter"

# Theme - ReadTheDocs style
remote_theme: rundocs/jekyll-rtd-theme
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# ReadTheDocs theme configuration
readme_index:
  with_frontmatter: true

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Getting Started"
    url: "/getting-started/"
    children:
      - title: "Authentication"
        url: "/getting-started/authentication/"
  - title: "Installation"
    url: "/installation/"
    children:
      - title: "Docker Compose"
        url: "/installation/docker-compose/"
      - title: "Docker"
        url: "/installation/docker/"
      - title: "Helm"
        url: "/installation/helm/"
      - title: "systemd"
        url: "/installation/systemd/"
      - title: "Binary"
        url: "/installation/binary/"

# GitHub integration
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/matanbaruch/netbird-api-exporter"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Footer
footer_content: "Copyright &copy; 2024 NetBird API Exporter. Distributed under the MIT License."

# External links
links:
  - title: "GitHub Repository"
    url: "https://github.com/matanbaruch/netbird-api-exporter"
  - title: "NetBird Documentation"
    url: "https://docs.netbird.io"

# Search
search_enabled: true

# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 