{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "netbird-api-exporter.fullname" . }}-external-secret
  labels:
    {{- include "netbird-api-exporter.labels" . | nindent 4 }}
    {{- with .Values.externalSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.secretName | default (include "netbird-api-exporter.secretName" .) }}
    creationPolicy: Owner
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 