{{- if and .Values.netbird.apiToken (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird-api-exporter.secretName" . }}
  labels:
    {{- include "netbird-api-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  netbird-api-token: {{ .Values.netbird.apiToken | b64enc | quote }}
{{- end }} 